language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - peter.rigole@atomicbits.io
after_success:
- echo "<settings><servers><server><id>ossrh</id><username>\${env.SONATYPE_USERNAME}</username><password>\${env.SONATYPE_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
- '[[ $TRAVIS_BRANCH == "develop" ]] && { mvn deploy --settings ~/settings.xml ; };'

env:
  global:
  - secure: VpmXM47xG1A5Wc6T376t4f2DSur0eFhUmD8moDz9G3wbUhTl1+jcql88oO/CCdMj9X2gYAyiyA1OJ4/nUzDNXmnk/XwpCjgIRpJoZVlynSHmcvKes5Y+o7hfmHa8Zbty91uCBlFbrDBvI3Tx5pyfjwgZU+gaa3qE4vL2Fw5xKIueONVvNgReHkSFu+/hk8G/E6FsBtrIfnwxRFTecBFc5I6tqMlbykdUbNkoSMNH5M0hfaDn6R8CfjKwOlLFZrwDbTn6c+AOjY6jJLGLZswcl2eWNFJoQpr7gFuyNPx2EgFux6OTnQZ8a22z28idTnRwiRmEJUM8sQlvj+KkyTKzEXFJv2ojVQo4kqtklXlRvF4cXt6XNgmiAYG4V3R6hIIRnIxuob/P94RsnTCF7Y0XO0Gzac4JCTrgZdiOYUmmn8QX/SBUT2xI1ObephZhWNOfYonbymvahgkBoCgsv6ncXGAEJvoKISOCw6EErDJjaawoyVG/cpdW7ufbGFFylhhlowTrxh2zCvhT4ygcuBFKSp/nFB5+Pe070zFSv6mfYxu+k13fpCIExJhcUYHyJbRhM6YlxGgG902L2CEhhT4Ms2aznS4v+eSRYjWrKd07rWfgF5kQaP1flp5AnVXPC/ceIjEXpWy0sK+WKSsdjZ1vhg7I0RISlezwH4ZlIvQxbAg=
  - secure: COL34wOHMxD9lEmBM1CKXtLRsSB9W/qDkd+l/QOU1Y1ap4i5lfcUySAg22s9eyAI7i3KDP1BflSSa4FsaKy6KdMx8XJF9wLNGr27m3Fy40LG9Mp4mdTx3HxPDARqaK6GHU+3T2L3UkHcalWto+TLdUriZZv/pwJtmgq1LW96CQUKX9GhVDlXwePuh5H1+0TVKYgCWToJVYVio/9dP0wYUdBChNeHocbtXbiS8T36pjYg2cxdFCGmo+EjKpvcp3azHj4yOnxYgsijhIzmt7YVxf5005rnmshRFYh6849leFKVpsS8754NzWZwQdXbjwaKQ2rHpydH5IpOGWBQmNwu4+hH3S707shk84qs8H3/nBGAIq03GSbZa2xGO+k5JXh2LEuqSzqXE5j72p1JD5yELXtaZBnsNnVoJuZ26M98VXTS5v9eltfwjRdylfupAEENwuBv99p3DsAMTCsUx2mECpzP2pS58SE7OdVZuxaGyNqAcFNN093KfFmBE3OB1DCNAzHrG7hVW3jvVhYIwp2YmNR7nLETzPWAfYy4kFCWRBlGpjhy3veWzO9fYTkxvZJ9GDaAL/zYD0vEN774sRm0NfyC1b5Z7mC6uEjYl+eX8asfRMLBBjWBZDripglIFTACyRijesnn0DhlQ1a2MJA8DclmlBPcYXxvSd3wd93kuZ0=
