language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - peter.rigole@atomicbits.io
after_success:
- '[[ $TRAVIS_BRANCH == "develop" ]] && { mvn deploy ; };'

env:
  global:
  - secure: vmOy5DGfflmvDuRebN8gj4mFGeV6w1e5NOSk/tLN/wRAhkRwXsxVp8140y4Q0sLYXoMbETDc2WifUtIJE7eT8pjif184vyj//AQ5F2xk9k0VqLpl4FEAoxjVmIXVcVpJ+Xc7CPD0f0cl4ILNhKRhw3BkMOUP3yVeGCAXkKjH5Kkf9vxpY7+U70Ph1kVEvB2Qv3fvgiug4hZZX21QQ8HT2SCFepJ9F2QSkv/jZReBqZs7md1lFKHA5PPYherCZDxTJmZCoEvXusdM2DT9DdCv2pBte53XzW6KEuwwW0dqfPO61kFOJ4g+ilWFj97js1Oe7xV6r0VsMNm/sYkyzuUmrAJF+gWNrbXhFBr3yLGQR7xR+3r2DmX1Gvh3EKWoJ9/FnkSO9daDjzgG8H6FitOUtMDNqfAaSYrsg7UNTyJeQMw6RIWd0X0h8J4FQvuY9ZjWCG7Gv1XGiVnL4ys90VNledhkm04bnztPyFzhFvealz9YDsqA4SQOZbbofA/Mv3IL0rq6Yh/EBUBwtoC4hkxqXfWZPL6/M4uFBgngKAFcBPRYMWsUsE50Kzsq5CO8VoaI07chsHERuLvS41YEOdYhA+vMXq6ZMbZNqlss7EBqNa+kzEkAFfnrLITLIjKq6VkqfMIObW5hiZK7yL8OJZd8Uim/2jg1Qx9JA2wMdmjwr0o=
  - secure: qoi92iXv94RAaXffFV2/3WKwk9npKmUmpR2/nM3T24TMTqBiLHCfbj+N7osAEbP2wlDEoJH+tYBPa5xz9cVJ2l6C50hssZNd8FT93qFj+pMKnL00p4bGthGqDdc9PXvClG6nYycYJUii4cdkXimB6w4JTaeMItua2vdWAclnK4hepkoRA2ykl2VrF1qd4TUnpPZA0LYLZqFWr1gP9TshEOByht6zYrTKjIiToCS20XhwqWUFk7xFpEYAV2jseWPVv+oMbQQDom7wFs/8IhLac4rOpEtD3uBANzitFQVjZkkJsGyNdG7wJ36NjjTJWnc8CevD3KrPs8EXDu9zwMYXBCvJAqV4srTh/ee1aZfYNVBTA9G5k/KvWzvZGBfXx1LhtSTr/Q6ovvbnfagtBfnplTn9FcK8mjwVNOgiVveMpaDU3UZ2IjFLKWfPekgxDUOdGMMeYUKWpiA8Ikh9WGauQSFyVOqO0V+6adg6l1wQ2a9F6G8I66jTVOpjryJFHNNRdtbcLUeS6ILinFpPpTv425c/+DBy9fBe3BqmmcOnFgCxdkhmlGxgxRTb/rDGZ8PkW39QFTu5nIHcxc08ne+B+pS/QtNe6N2c2yA2qiXsrTuYK3TpJLz0tFTmoAGfsLRD70LOBDWxy1RmKY2xK945NF4iMIJoBr8zWUHX94d73Ic=
